apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-py
  labels:
    app: django-py
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-py
  template:
    metadata:
      labels:
        app: django-py
    spec:
      containers:
      - name: django-py
        image: syam32/kubedj:v1
        ports:
        - containerPort: 8080
